---
- hosts: all
  become: yes
  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        update_cache: yes
    - name: Install numpy
      pip:
        name: numpy
    - name: Install scipy
      pip:
        name: scipy
    - name: Install netcdf4
      pip:
        name: netcdf4 